### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by rushtamas** [augisbud/m365_dashboard#52]
Hello,
I buld it and it says no data, and the screen flashing.
When I press the button on the arduino, rebooting continuously.
What could be the problem?

**Comment by villamany** [comment]
Post a picture of your wiring and diode/resistor position

**Comment by smidak** [comment]
I have the same problem. Pressing the adrduino reset button starts and does not function again when the power is cut off(no data)

**Comment by NetBUG** [comment]
Hi guys,
this is 100% a hardware problem with the connection between the bus and controller.
Pressing any buttons won't work, since is does not change anything about the data.
If you use an ATMega32U8-based board - double-check the connection (diode and resistor) and ensure the value is correct (100-150 Ohm, not 150K! :) )
If you use a board with Mega328P - ensure that the pins are not puled down by the USB-TTL converter. If you have a board with that, it's advised to use SoftwareSerial on another pins (e.g. 2-3) rather than the hardware Serial.

**Comment by villamany** [comment]
I'm using the diode and 220ohm resistor in TX line and another 220ohm resistor in RX line and working fine (i prefer to limit any current on both pins)

**Comment by rushtamas** [comment]
I checked the diode polarity, the ohm resistance, tried with another board. Now "Bus not connected" screen shows, and can't turn off the M365 until I'm not plugging out the cables. But the screen not flickering, and not rebooting.

![20190503_153310](https://user-images.githubusercontent.com/8601196/57142096-0237c780-6dbc-11e9-8628-f291825e6c77.jpg)

**Comment by villamany** [comment]
Check the previous @NetBUG reply. 
You are using a NANO board with USB, the USB-UART chip uses the same TX and RX pins that you are trying to use for the M365 communication. The standard assembly uses an Arduino MINI tbat doesn't have USB.

**Comment by rushtamas** [comment]
Okay, thx! I'll try it with arduino without usb on monday!

**Comment by villamany** [comment]
As described by @NetBUG you can use software serial port on other pins or simply cut the traces fom TX/RX pins to the USB chip and use bootloader with an FTDI device or ICSP method

**Comment by smidak** [comment]
![IMG_20190503_190343 1](https://user-images.githubusercontent.com/48006495/57160149-3f19b380-6de8-11e9-88db-b3286f0bac48.jpg)

**Comment by smidak** [comment]
![IMG_20190503_190326 1](https://user-images.githubusercontent.com/48006495/57160219-72f4d900-6de8-11e9-94b0-1d0021244997.jpg)

**Comment by augisbud** [comment]
is the diode and the resistor correct? @smidak

**Comment by smidak** [comment]
Yes, 2x220ohm+ TX diode😭
